require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Cpanel::NotificationsController do

  # This should return the minimal set of attributes required to create a valid
  # Cpanel::Notification. As you add validations to Cpanel::Notification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cpanel::NotificationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cpanel_notifications as @cpanel_notifications" do
      notification = Cpanel::Notification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cpanel_notifications).should eq([notification])
    end
  end

  describe "GET show" do
    it "assigns the requested cpanel_notification as @cpanel_notification" do
      notification = Cpanel::Notification.create! valid_attributes
      get :show, {:id => notification.to_param}, valid_session
      assigns(:cpanel_notification).should eq(notification)
    end
  end

  describe "GET new" do
    it "assigns a new cpanel_notification as @cpanel_notification" do
      get :new, {}, valid_session
      assigns(:cpanel_notification).should be_a_new(Cpanel::Notification)
    end
  end

  describe "GET edit" do
    it "assigns the requested cpanel_notification as @cpanel_notification" do
      notification = Cpanel::Notification.create! valid_attributes
      get :edit, {:id => notification.to_param}, valid_session
      assigns(:cpanel_notification).should eq(notification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cpanel::Notification" do
        expect {
          post :create, {:cpanel_notification => valid_attributes}, valid_session
        }.to change(Cpanel::Notification, :count).by(1)
      end

      it "assigns a newly created cpanel_notification as @cpanel_notification" do
        post :create, {:cpanel_notification => valid_attributes}, valid_session
        assigns(:cpanel_notification).should be_a(Cpanel::Notification)
        assigns(:cpanel_notification).should be_persisted
      end

      it "redirects to the created cpanel_notification" do
        post :create, {:cpanel_notification => valid_attributes}, valid_session
        response.should redirect_to(Cpanel::Notification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cpanel_notification as @cpanel_notification" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Notification.any_instance.stub(:save).and_return(false)
        post :create, {:cpanel_notification => {}}, valid_session
        assigns(:cpanel_notification).should be_a_new(Cpanel::Notification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Notification.any_instance.stub(:save).and_return(false)
        post :create, {:cpanel_notification => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cpanel_notification" do
        notification = Cpanel::Notification.create! valid_attributes
        # Assuming there are no other cpanel_notifications in the database, this
        # specifies that the Cpanel::Notification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cpanel::Notification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => notification.to_param, :cpanel_notification => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cpanel_notification as @cpanel_notification" do
        notification = Cpanel::Notification.create! valid_attributes
        put :update, {:id => notification.to_param, :cpanel_notification => valid_attributes}, valid_session
        assigns(:cpanel_notification).should eq(notification)
      end

      it "redirects to the cpanel_notification" do
        notification = Cpanel::Notification.create! valid_attributes
        put :update, {:id => notification.to_param, :cpanel_notification => valid_attributes}, valid_session
        response.should redirect_to(notification)
      end
    end

    describe "with invalid params" do
      it "assigns the cpanel_notification as @cpanel_notification" do
        notification = Cpanel::Notification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Notification.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification.to_param, :cpanel_notification => {}}, valid_session
        assigns(:cpanel_notification).should eq(notification)
      end

      it "re-renders the 'edit' template" do
        notification = Cpanel::Notification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Notification.any_instance.stub(:save).and_return(false)
        put :update, {:id => notification.to_param, :cpanel_notification => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cpanel_notification" do
      notification = Cpanel::Notification.create! valid_attributes
      expect {
        delete :destroy, {:id => notification.to_param}, valid_session
      }.to change(Cpanel::Notification, :count).by(-1)
    end

    it "redirects to the cpanel_notifications list" do
      notification = Cpanel::Notification.create! valid_attributes
      delete :destroy, {:id => notification.to_param}, valid_session
      response.should redirect_to(cpanel_notifications_url)
    end
  end

end
