require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Cpanel::TagsController do

  # This should return the minimal set of attributes required to create a valid
  # Cpanel::Tag. As you add validations to Cpanel::Tag, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cpanel::TagsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cpanel_tags as @cpanel_tags" do
      tag = Cpanel::Tag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cpanel_tags).should eq([tag])
    end
  end

  describe "GET show" do
    it "assigns the requested cpanel_tag as @cpanel_tag" do
      tag = Cpanel::Tag.create! valid_attributes
      get :show, {:id => tag.to_param}, valid_session
      assigns(:cpanel_tag).should eq(tag)
    end
  end

  describe "GET new" do
    it "assigns a new cpanel_tag as @cpanel_tag" do
      get :new, {}, valid_session
      assigns(:cpanel_tag).should be_a_new(Cpanel::Tag)
    end
  end

  describe "GET edit" do
    it "assigns the requested cpanel_tag as @cpanel_tag" do
      tag = Cpanel::Tag.create! valid_attributes
      get :edit, {:id => tag.to_param}, valid_session
      assigns(:cpanel_tag).should eq(tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cpanel::Tag" do
        expect {
          post :create, {:cpanel_tag => valid_attributes}, valid_session
        }.to change(Cpanel::Tag, :count).by(1)
      end

      it "assigns a newly created cpanel_tag as @cpanel_tag" do
        post :create, {:cpanel_tag => valid_attributes}, valid_session
        assigns(:cpanel_tag).should be_a(Cpanel::Tag)
        assigns(:cpanel_tag).should be_persisted
      end

      it "redirects to the created cpanel_tag" do
        post :create, {:cpanel_tag => valid_attributes}, valid_session
        response.should redirect_to(Cpanel::Tag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cpanel_tag as @cpanel_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Tag.any_instance.stub(:save).and_return(false)
        post :create, {:cpanel_tag => {}}, valid_session
        assigns(:cpanel_tag).should be_a_new(Cpanel::Tag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Tag.any_instance.stub(:save).and_return(false)
        post :create, {:cpanel_tag => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cpanel_tag" do
        tag = Cpanel::Tag.create! valid_attributes
        # Assuming there are no other cpanel_tags in the database, this
        # specifies that the Cpanel::Tag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cpanel::Tag.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tag.to_param, :cpanel_tag => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cpanel_tag as @cpanel_tag" do
        tag = Cpanel::Tag.create! valid_attributes
        put :update, {:id => tag.to_param, :cpanel_tag => valid_attributes}, valid_session
        assigns(:cpanel_tag).should eq(tag)
      end

      it "redirects to the cpanel_tag" do
        tag = Cpanel::Tag.create! valid_attributes
        put :update, {:id => tag.to_param, :cpanel_tag => valid_attributes}, valid_session
        response.should redirect_to(tag)
      end
    end

    describe "with invalid params" do
      it "assigns the cpanel_tag as @cpanel_tag" do
        tag = Cpanel::Tag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Tag.any_instance.stub(:save).and_return(false)
        put :update, {:id => tag.to_param, :cpanel_tag => {}}, valid_session
        assigns(:cpanel_tag).should eq(tag)
      end

      it "re-renders the 'edit' template" do
        tag = Cpanel::Tag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpanel::Tag.any_instance.stub(:save).and_return(false)
        put :update, {:id => tag.to_param, :cpanel_tag => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cpanel_tag" do
      tag = Cpanel::Tag.create! valid_attributes
      expect {
        delete :destroy, {:id => tag.to_param}, valid_session
      }.to change(Cpanel::Tag, :count).by(-1)
    end

    it "redirects to the cpanel_tags list" do
      tag = Cpanel::Tag.create! valid_attributes
      delete :destroy, {:id => tag.to_param}, valid_session
      response.should redirect_to(cpanel_tags_url)
    end
  end

end
